[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo_sqlite", "php83Extensions.sqlite3", "php83Extensions.mbstring", "php83Extensions.tokenizer", "php83Extensions.xml", "php83Extensions.ctype", "php83Extensions.fileinfo", "php83Extensions.openssl", "php83Extensions.bcmath", "php83Extensions.json", "composer"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "mkdir -p storage && test -f storage/database.sqlite || touch storage/database.sqlite && chmod 777 storage/database.sqlite && php artisan config:clear && php artisan route:clear && php artisan migrate --force && php -d variables_order=EGPCS -S 0.0.0.0:${PORT:-8080} -t public/ public/index.php"
